### ISSUE TITLE
Breaks on the latest version of react.

### ISSUE THREAD

**Issue by Pixelatex** [davidhu2000/react-spinners#14]
I couldn't build my project anymore and after some digging, it seems like this module was the origin. Removing it instantly fixed everything, the strange thing is that this only occurred after I ran npm update. So it seems like your dev dependencies being outdated is causing some breaking issues.

**Comment by davidhu2000** [comment]
Hi @Pixelatex, can you provide more details? 

For example, what version of React were you using? 

What version of `react-spinners` were you using? 

Was there any deprecation warnings in the terminal output? 

The earlier `0.1.x` versions were a little buggy. 

I don't quite understand why devDependencies are causing issues since they should be installed in the development environment. 

For example, if I start new project and run `npm install react-spinners`, `eslint`, a devDependency is not in the `node_modules` folder.

**Comment by GiovanniFrigo** [comment]
I had a similar issue, and for me just installing the latest `prop-types` module fixed the issue. 

Hope this can help you, @Pixelatex

**Comment by davidhu2000** [comment]
does this mean that `prop-types` need to be added as a dependency?

**Comment by Pixelatex** [comment]
I think that you were relying on a now deprecated module feature which would explain why updating it breaks it. I can't recall what the issue was exactly but it was not something I could fix instantly so I had to drop your module from my project. I will try a test tomorrow and post the error if I can duplicate it again.

**Comment by GiovanniFrigo** [comment]
> does this mean that prop-types need to be added as a dependency?
yes I think so.

You're using it in the code (like [here](https://github.com/davidhu2000/react-spinners/blob/master/src/spinners/BarLoader.jsx#L2)) but the package is not referenced in package.json. 

I think it should be a peerDependency just like `react` and `react-dom`

**Comment by davidhu2000** [comment]
looks like `prop-types` repo recommends that the package be added to dependencies. Will fix this

**Comment by davidhu2000** [comment]
This issue is fixed in `0.2.1`.
